### ISSUE TITLE
Agenda displays the first day instead of the current day when first used

### ISSUE THREAD

**Issue by Xeon0X** [onyx-lyon1/onyx#1]
**Steps to reproduce**

- Open the application
- Add a new calendar with the URL: the correct day is displayed.
- Restart the application
- The first day of the calendar is displayed instead of the current day, even after several reloads.

The problem is probably solved after clicking on an event.

https://user-images.githubusercontent.com/63558210/206856786-78deb7e7-d147-4e43-bf6a-e830e4502bb9.mp4

**Comment by hatch01** [comment]
Unable to reproduce
