### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by Xeon0X** [onyx-lyon1/onyx#24]
Space before ":" 
![Screenshot_20230119_141555](https://user-images.githubusercontent.com/63558210/213454753-45d32ab6-df06-4ca0-80dd-8afc1911a4f7.jpg)

"claire" instead of "claire" and "système" instead of "system"
![Screenshot_20230119_141854](https://user-images.githubusercontent.com/63558210/213455111-4537b0ef-2316-4f4f-b4f5-04110c0a1513.jpg)

Forgotten accent:
![Screenshot_20230119_141925](https://user-images.githubusercontent.com/63558210/213455447-2fbd14cb-07ab-4fe6-ad02-4f081bf2bf3f.jpg)
![Screenshot_20230119_142026](https://user-images.githubusercontent.com/63558210/213455479-f8765f47-7304-425a-b77b-4b9fed0e347a.jpg)
![Screenshot_20230119_142045](https://user-images.githubusercontent.com/63558210/213455521-8d939872-9bb5-459e-b232-d63b0c355f6b.jpg)

"Choisir le thème" instead of "Activer le thème sombre"
![Screenshot_20230119_142154](https://user-images.githubusercontent.com/63558210/213456136-86aa7744-c519-4033-a082-c9dfaa0b0832.jpg)

"999.00" instead of "999.0"
![Screenshot_20230119_142649](https://user-images.githubusercontent.com/63558210/213456549-61c14783-d938-495b-803b-0f7f06f074f5.jpg)

"carte" instead of "Carte"
![Screenshot_20230119_142709](https://user-images.githubusercontent.com/63558210/213456681-b9b00f00-ffa4-4e24-9496-ee3edf496d27.jpg)

Change "Recharger par un virement" in "Tiers" category
![Screenshot_20230119_141958](https://user-images.githubusercontent.com/63558210/213458033-1860e5fc-4e36-4314-a02d-1065b8e97b7c.jpg)

"Emails" instead of "mails", in Paramètres and "Emails" section
![Screenshot_20230119_142745](https://user-images.githubusercontent.com/63558210/213457614-ca1efd8f-694e-4f74-b846-cfaf8c073cc1.jpg)

"événements" instead of "évènements

**Comment by Xeon0X** [comment]
"Réponse" instead of "reponse" in emails

**Comment by hatch01** [comment]
done !
