### ISSUE TITLE
Wrong color displayed in some grades for an unknown reason

### ISSUE THREAD

**Issue by Xeon0X** [onyx-lyon1/onyx#3]
![tempFileForShare_20221210-144742](https://user-images.githubusercontent.com/63558210/206860459-fba0a231-a07d-4dd4-b84b-33df844f0a87.jpg)

This grade appears in dark red on TOMUSS. Another user had the same problem with it in another subject. The only common point was the grade: 3, but out of 10 instead of 16.

**Comment by hatch01** [comment]
fixed in last commit 3ce891c7da701c33581e35fba2d11822c47a075d
