### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [onyx-lyon1/onyx#43]
```
Resolving dependencies...
The current Dart SDK version is 3.2.3.

Because share_plus 10.0.2 requires SDK version >=3.3.0 <4.0.0 and no versions of share_plus match >10.0.2 <11.0.0, share_plus ^10.0.2 is forbidden.
So, because onyx depends on share_plus ^10.0.2, version solving failed.
```
The whole point of the flutter submodule is to be used in your CI workflow too so you don't forget to update it and F-Droid can build the app.

Currently it's 9 months old: https://github.com/onyx-lyon1/onyx/tree/main/apps

/LE: https://gitlab.com/fdroid/fdroiddata/-/commit/2013ca6ac50080c2b83ec1c3b08dcee2e777f3a6

**Comment by licaon-kter** [comment]
can we reopen?

ref: https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8419637166

**Comment by hatch01** [comment]
I will quickly fix de submodule.
When I will have time, I will use nix for fdroid build to be sure that the versions always match my dev environnement

**Comment by licaon-kter** [comment]
> I will use nix for fdroid build

in your build pipeline locally or? :smile:

**Comment by hatch01** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16867
I just openned a fix MR on fdroiddata

**Comment by licaon-kter** [comment]
thanks
