### ISSUE TITLE
Add better grade management

### ISSUE THREAD

**Issue by Xeon0X** [onyx-lyon1/onyx#5]
The grades are very nicely displayed on Onyx, however, they do not necessarily reflect the reality of TOMUSS. 

![image](https://user-images.githubusercontent.com/63558210/206861834-4aa4d4f5-e1b1-446b-acea-494b51f9b362.png)

Indeed, some grades are the sum of other grades, others have different coefficients, or even do not count.

As it seems difficult to me to automate this process, given that the way grades are taken into account on TOMUSS itself does not necessarily reflect the way they are taken into account within the university, it may be possible to let the user decide the coefficient or the percentage that each grade represents in the final grade of the subject, the one displayed in the main menu on Onyx.

In this way, the main menu of Onyx could reflect more realistically what is taken into account within the university, or at least, could allow the user to make his own opinion about his grades. The goal is simply to avoid the user to take out his calculator or his excel table.

Another important consideration is that the user should be aware of how the averages displayed on the main screen are calculated. Since these are not grades from TOMUSS but locally calculated grades, they should not mislead an uninformed user. Allowing him to configure the weight of each grade is a way to make him understand that it is not an official grade. But if this option is too complicated to set up, I think it is necessary to warn that it is not an official grade.

**Comment by hatch01** [comment]
Implemented in dartus lib : 7d52a6707e3d371d3d19caa970aa0284ce44f855
Now need to implement in onyx

**Comment by hatch01** [comment]
done : c450baa6c273392fc0ad2c836f1c023b99e40eb4
