### ISSUE TITLE
UI improvement for grades

### ISSUE THREAD

**Issue by Xeon0X** [onyx-lyon1/onyx#8]
- The title of the note category is hidden behind the top notification bar.

![image](https://user-images.githubusercontent.com/63558210/211164615-830a5aeb-2ea8-4edd-81ae-eeb44939b236.png)

- The color of the average on the main screen does not reflect the applied coefficient.
- The icon to change semester seems too much on the right (no margin)

![image](https://user-images.githubusercontent.com/63558210/211165387-cf33119d-ae2e-4bc5-ba05-d83b0d0c848e.png)

- The same spacing between the right side and top and bottom could increase visual consistency. The same can be said for the choice of semesters (have something more square).

![image](https://user-images.githubusercontent.com/63558210/211165585-39bd04b4-ba1b-43cc-98fb-2f0bdd1ffff9.png)

- Capital letters could be added in the information of each grade.

![image](https://user-images.githubusercontent.com/63558210/211165781-2b80f81b-91c8-4325-98b4-c2f838922727.png)

**Comment by hatch01** [comment]
fixed
